"""empty message

Revision ID: 16b38413ba51
Revises: 56b8560537e2
Create Date: 2024-01-08 14:33:07.437305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16b38413ba51'
down_revision = '56b8560537e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('data_criacao', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'data_criacao')
    # ### end Alembic commands ###
