"""empty message

Revision ID: 1d7cb4159ccf
Revises: 5f32d50b3320
Create Date: 2024-01-13 18:15:10.125134

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1d7cb4159ccf'
down_revision = '5f32d50b3320'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('create_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('usuario', sa.Column('update_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('usuario', 'data_criacao')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('data_criacao', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_column('usuario', 'update_at')
    op.drop_column('usuario', 'create_at')
    # ### end Alembic commands ###
