"""empty message

Revision ID: 5da863f3aa94
Revises: c3aaec357417
Create Date: 2024-01-30 17:56:18.525332

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5da863f3aa94'
down_revision = 'c3aaec357417'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_user_role_user', 'user_roles', type_='foreignkey')
    op.create_foreign_key(None, 'user_roles', 'usuario', ['user_id'], ['id'])
    op.drop_column('usuario', 'update_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('update_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user_roles', type_='foreignkey')
    op.create_foreign_key('fk_user_role_user', 'user_roles', 'usuario', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
