"""empty message

Revision ID: c3aaec357417
Revises: 1899d2c9e60f
Create Date: 2024-01-21 14:17:05.940788

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c3aaec357417'
down_revision = '1899d2c9e60f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'update_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('update_at', mysql.DATETIME(), nullable=True))
    # ### end Alembic commands ###
